services:
  justintime.user:
    image: ${DOCKER_REGISTRY-}justintimeuser
    build:
      context: .
      dockerfile: JustInTime.User/Dockerfile
    networks:
      - justintime_network
    ports:
      - "7001:7001"

  justintime.gateway:
    image: ${DOCKER_REGISTRY-}justintimegateway
    build:
      context: .
      dockerfile: JustInTime.Gateway/Dockerfile
    networks:
      - justintime_network
    ports:
      - "7000:7000"


  justintime.auth:
    image: ${DOCKER_REGISTRY-}justintimeauth
    build:
      context: .
      dockerfile: JustInTime.Auth/Dockerfile
    networks:
      - justintime_network
    ports:
      - "7002:7002"


  justintime.ponto:
    image: ${DOCKER_REGISTRY-}justintimeponto
    build:
      context: .
      dockerfile: JustInTime.Ponto/Dockerfile
    networks:
      - justintime_network
    ports:
      - "7003:7003"

networks:
  justintime_network:
    driver: bridge

